// Auto-extracted from the live site's hardcoded menu arrays.
// banner/icon/assets values are not needed for seeding the database
// (admin panel never touches images), so they resolve to a harmless empty string.

type MenuItem = {
  name: string;
  price?: string;
  price_750ml?: string;
  price_180ml?: string;
  price_90ml?: string;
  price_60ml?: string;
  price_30ml?: string;
  price_150ml?: string;
};

type MenuSection = {
  id: string;
  title: string;
  banner?: string;
  icon?: string;
  items: MenuItem[];
};

const rs = "₹";
const assets: Record<string, string> = new Proxy({}, { get: () => "" });

const menuSections: MenuSection[] = [
  {
    id: "hot-beverages",
    title: "Hot Beverages",
    banner: assets.imgHotBeverages,
    icon: assets.imgHotBeverages,
    items: [
      { name: "Coffee / Tea", price: `${rs}30` },
      { name: "Plain Milk", price: `${rs}40` },
      { name: "Horlicks", price: `${rs}40` },
      { name: "Black Coffee", price: `${rs}40` },
      { name: "Lemon Tea", price: `${rs}40` },
      { name: "Ginger Tea", price: `${rs}40` },
      { name: "Black Tea", price: `${rs}40` },
      { name: "Boost", price: `${rs}40` },
      { name: "Badam Milk", price: `${rs}40` },
    ],
  },
  {
    id: "desserts",
    title: "Sweets",
    banner: assets.imgDesserts,
    icon: assets.imgDesserts,
    items: [
      { name: "Carrot Halwa", price: `${rs}70` },
      { name: "Jamoon", price: `${rs}50` },
      { name: "Dry Jamoon", price: `${rs}50` },
    ],
  },
  {
    id: "breakfast",
    title: "Breakfast",
    banner: assets.imgBreakfast,
    icon: assets.imgBreakfast,
    items: [
      { name: "Idly (1)", price: `${rs}35` },
      { name: "Idly (2)", price: `${rs}70` },
      { name: "Vada (1)", price: `${rs}35` },
      { name: "Vada (2)", price: `${rs}60` },
      { name: "Idly 2 + Vada 1", price: `${rs}90` },
      { name: "Idly 1 + Vada 1", price: `${rs}70` },
      { name: "Rava Idly", price: `${rs}60` },
      { name: "Poori Sagu", price: `${rs}90` },
      { name: "Khara Bath", price: `${rs}50` },
      { name: "Kesari Bath", price: `${rs}50` },
      { name: "Chow Chow Bath", price: `${rs}100` },
      { name: "Bisibele Bath", price: `${rs}70` },
      { name: "Veg Pongal", price: `${rs}70` },
      { name: "Buns", price: `${rs}60` },
      { name: "Shavige Bath", price: `${rs}60` },
      { name: "Avalaki Bath", price: `${rs}60` },
    ],
  },
  {
    id: "dosa-corner",
    title: "Dosa Corner",
    banner: assets.imgDosa,
    icon: assets.imgDosa,
    items: [
      { name: "Set Dosa", price: `${rs}90` },
      { name: "Plain Dosa", price: `${rs}90` },
      { name: "Butter Plain Dosa", price: `${rs}110` },
      { name: "Cheese Plain Dosa", price: `${rs}120` },
      { name: "Pudi Plain Dosa", price: `${rs}110` },
      { name: "Butter Masala Dosa", price: `${rs}130` },
      { name: "Pudi Masala Dosa", price: `${rs}120` },
      { name: "Cheese Masala Dosa", price: `${rs}150` },
      { name: "Open Butter Masala Dosa", price: `${rs}120` },
      { name: "Onion Uttapam", price: `${rs}100` },
      { name: "Masala Dosa", price: `${rs}110` },
      { name: "Open Masala Dosa", price: `${rs}120` },
      { name: "Onion Rava Dosa", price: `${rs}120` },
      { name: "Rawa Dosa", price: `${rs}110` },
      { name: "Kali Dose", price: `${rs}90` },
    ],
  },
  {
    id: "meals-extras",
    title: "Meals + Extras",
    banner: assets.imgMeals,
    icon: assets.imgMeals,
    items: [
      { name: "Special Deluxe Shivapakam Thali", price: `${rs}250` },
      { name: "South Meals", price: `${rs}160` },
      { name: "North Meals", price: `${rs}220` },
      { name: "Rice", price: `${rs}30` },
      { name: "Poori", price: `${rs}30` },
      { name: "Curd (Cup)", price: `${rs}20` },
      { name: "Pappad", price: `${rs}20` },
      { name: "Bhaji", price: `${rs}20` },
      { name: "Gravy", price: `${rs}20` },
      { name: "Payasa", price: `${rs}30` },
    ],
  },
  {
    id: "south-indian-snacks",
    title: "South Indian Snacks",
    banner: assets.imgSnacks,
    icon: assets.imgSnacks,
    items: [
      { name: "Bonda Soup (2pc)", price: `${rs}60` },
      { name: "Chilli Bajji / Mirchi (4pc)", price: `${rs}80` },
      { name: "Masala Vada (4pc)", price: `${rs}70` },
      { name: "Madhur Vada (2pc)", price: `${rs}60` },
      { name: "Onion Pakoda", price: `${rs}60` },
      { name: "Palak Pakoda", price: `${rs}60` },
      { name: "Mangalore Bhaji (4pc)", price: `${rs}60` },
      { name: "Aloo Bhaji (2pc)", price: `${rs}60` },
    ],
  },
  {
    id: "soups",
    title: "Soups",
    banner: assets.imgSoups,
    icon: assets.imgSoups,
    items: [
      { name: "Cream of Tomato Soup", price: `${rs}120` },
      { name: "Veg Manchow Soup", price: `${rs}120` },
      { name: "Veg Clear Soup", price: `${rs}120` },
      { name: "Hot & Sour Soup", price: `${rs}120` },
      { name: "Lemon Coriander Soup", price: `${rs}120` },
      { name: "Veg Sweet Corn Soup", price: `${rs}120` },
      { name: "Cream of Mushroom Soup", price: `${rs}130` },
    ],
  },
  {
    id: "chinese-starters",
    title: "Chinese Starters",
    banner: assets.imgChinese,
    icon: assets.imgChinese,
    items: [
      { name: "Gobi Manchurian", price: `${rs}160` },
      { name: "Gobi Chilli", price: `${rs}160` },
      { name: "Gobi 65", price: `${rs}160` },
      { name: "Gobi Pepper Dry", price: `${rs}160` },
      { name: "Paneer Manchurian", price: `${rs}240` },
      { name: "Paneer Chilli", price: `${rs}250` },
      { name: "Paneer 65", price: `${rs}250` },
      { name: "Paneer Pepper Dry", price: `${rs}250` },
      { name: "Babycorn Manchurian", price: `${rs}180` },
      { name: "Babycorn Chilli", price: `${rs}180` },
      { name: "Babycorn 65", price: `${rs}180` },
      { name: "Baby Corn Pepper Dry", price: `${rs}180` },
      { name: "Mushroom Manchurian", price: `${rs}200` },
      { name: "Mushroom Chilli", price: `${rs}200` },
      { name: "Mushroom 65", price: `${rs}200` },
      { name: "Mushroom Pepper Dry", price: `${rs}220` },
      { name: "Veg Ball Manchurian", price: `${rs}180` },
      { name: "Crispy Veg", price: `${rs}200` },
      { name: "Crispy Babycorn", price: `${rs}200` },
      { name: "Crispy Corn", price: `${rs}200` },
      { name: "Honey Chilli Potato", price: `${rs}200` },
      { name: "French / Peri Peri Fries", price: `${rs}150` },
    ],
  },
  {
    id: "salads",
    title: "Salads",
    banner: assets.imgSalad,
    icon: assets.imgSalad,
    items: [
      { name: "Green Salad", price: `${rs}70` },
      { name: "Cucumber Salad", price: `${rs}70` },
    ],
  },
  {
    id: "tandoori-starters",
    title: "Tandoori Starters",
    banner: assets.imgStarters,
    icon: assets.imgStarters,
    items: [
      { name: "Paneer Tikka", price: `${rs}260` },
      { name: "Paneer Hariyali Tikka", price: `${rs}260` },
      { name: "Paneer Achari Tikka", price: `${rs}260` },
      { name: "Paneer Malai Tikka", price: `${rs}280` },
      { name: "Tandoori Baby Corn", price: `${rs}270` },
      { name: "Stuffed Mushroom", price: `${rs}270` },
      { name: "Hara Bara Kabab", price: `${rs}260` },
    ],
  },
  {
    id: "north-indian-starters",
    title: "North Indian Starters",
    banner: assets.imgStarters,
    icon: assets.imgStarters,
    items: [
      { name: "Aloo Jeera Dry", price: `${rs}200` },
      { name: "Paneer Ghee Roast", price: `${rs}280` },
      { name: "Mushroom Ghee Roast", price: `${rs}280` },
      { name: "Paneer Tawa Subzi", price: `${rs}320` },
      { name: "Masala Papad", price: `${rs}60` },
      { name: "Roasted Papad", price: `${rs}40` },
      { name: "Roasted Masala Papad", price: `${rs}70` },
      { name: "Fried Papad", price: `${rs}60` },
    ],
  },
  {
    id: "dal",
    title: "Dal",
    banner: assets.imgDal,
    icon: assets.imgDal,
    items: [
      { name: "Dal Fry", price: `${rs}180` },
      { name: "Dal Tadka", price: `${rs}190` },
      { name: "Dal Palak", price: `${rs}200` },
      { name: "Dal Punjabi", price: `${rs}200` },
      { name: "Dal Kolhapuri", price: `${rs}200` },
    ],
  },
  {
    id: "paneer",
    title: "Paneer",
    banner: assets.imgPaneer,
    icon: assets.imgPaneer,
    items: [
      { name: "Paneer Butter Masala", price: `${rs}250` },
      { name: "Paneer Tikka Masala", price: `${rs}260` },
      { name: "Paneer Pasand", price: `${rs}280` },
      { name: "Paneer Peshawari", price: `${rs}230` },
      { name: "Palak Paneer", price: `${rs}240` },
      { name: "Shahi Paneer", price: `${rs}260` },
      { name: "Mutter Paneer Masala", price: `${rs}280` },
      { name: "Paneer Hyderabadi Masala", price: `${rs}270` },
      { name: "Kaju Paneer", price: `${rs}300` },
      { name: "Paneer Shahi Kurma", price: `${rs}300` },
      { name: "Paneer Methi Hariyali", price: `${rs}290` },
      { name: "Paneer Jalfrezi", price: `${rs}250` },
    ],
  },
  {
    id: "mix-veg-curry",
    title: "Mix Veg Curry",
    banner: assets.imgCurry,
    icon: assets.imgCurry,
    items: [
      { name: "Green Peas Masala", price: `${rs}190` },
      { name: "Aloo Gobi Masala", price: `${rs}200` },
      { name: "Veg Kolhapuri", price: `${rs}200` },
      { name: "Plain Palak", price: `${rs}180` },
      { name: "Aloo Palak", price: `${rs}180` },
      { name: "Mix Veg Palak", price: `${rs}240` },
      { name: "Veg Patiyala", price: `${rs}250` },
      { name: "Paneer Patiyala", price: `${rs}250` },
      { name: "Veg Kurma", price: `${rs}260` },
      { name: "Veg Do Pyaza", price: `${rs}250` },
      { name: "Channa Masala", price: `${rs}180` },
      { name: "Capsicum Masala", price: `${rs}200` },
      { name: "Methi Malai Matar", price: `${rs}260` },
      { name: "Kaju Masala", price: `${rs}290` },
      { name: "Veg Shahi Kurma", price: `${rs}240` },
      { name: "Veg Hyderabadi Masala", price: `${rs}270` },
      { name: "Veg Jalfrezi", price: `${rs}250` },
      { name: "Veg Tawa Masala", price: `${rs}250` },
    ],
  },
  {
    id: "mushroom",
    title: "Mushroom",
    banner: assets.imgMash,
    icon: assets.imgMash,
    items: [
      { name: "Mushroom Tikka Masala", price: `${rs}250` },
      { name: "Kaju Mushroom Masala", price: `${rs}300` },
      { name: "Mushroom Masala", price: `${rs}240` },
    ],
  },
  {
    id: "kadai-special",
    title: "Kadai Special",
    banner: assets.imgKadai,
    icon: assets.imgKadai,
    items: [
      { name: "Kadai Mix Veg", price: `${rs}200` },
      { name: "Kadai Paneer", price: `${rs}250` },
      { name: "Kadai Mushroom", price: `${rs}240` },
    ],
  },
  {
    id: "koftha",
    title: "Koftha",
    banner: assets.imgPaneer,
    icon: assets.imgPaneer,
    items: [
      { name: "Veg Koftha", price: `${rs}260` },
      { name: "Paneer Koftha", price: `${rs}280` },
      { name: "Veg Malai Koftha", price: `${rs}270` },
    ],
  },
  {
    id: "breads",
    title: "Breads",
    banner: assets.imgBreads,
    icon: assets.imgBreads,
    items: [
      { name: "Plain Roti", price: `${rs}35` },
      { name: "Butter Roti", price: `${rs}45` },
      { name: "Kulcha", price: `${rs}40` },
      { name: "Butter Kulcha", price: `${rs}50` },
      { name: "Masala Kulcha", price: `${rs}80` },
      { name: "Onion Kulcha", price: `${rs}80` },
      { name: "Plain Naan", price: `${rs}50` },
      { name: "Butter Naan", price: `${rs}60` },
      { name: "Garlic Naan", price: `${rs}80` },
      { name: "Butter Garlic Naan", price: `${rs}90` },
      { name: "Stuffed Naan", price: `${rs}90` },
      { name: "Methi Roti", price: `${rs}50` },
      { name: "Methi Butter Roti", price: `${rs}60` },
      { name: "Pudina Roti", price: `${rs}50` },
      { name: "Lacha Paratha", price: `${rs}80` },
      { name: "Aloo Paratha", price: `${rs}100` },
    ],
  },
  {
    id: "rice",
    title: "Rice",
    banner: assets.imgRice,
    icon: assets.imgRice,
    items: [
      { name: "Jeera Rice", price: `${rs}160` },
      { name: "Ghee Rice", price: `${rs}180` },
      { name: "Veg Fried Rice", price: `${rs}180` },
      { name: "Paneer Fried Rice", price: `${rs}210` },
      { name: "Mushroom Fried Rice", price: `${rs}200` },
      { name: "Babycorn Fried Rice", price: `${rs}200` },
      { name: "Veg Schezwan Fried Rice", price: `${rs}190` },
      { name: "Paneer Schezwan Fried Rice", price: `${rs}210` },
      { name: "Singapore Fried Rice", price: `${rs}210` },
    ],
  },
  {
    id: "noodles",
    title: "Noodles",
    banner: assets.imgNoodles,
    icon: assets.imgNoodles,
    items: [
      { name: "Veg Noodles", price: `${rs}180` },
      { name: "Hakka Noodles", price: `${rs}180` },
      { name: "Paneer Noodles", price: `${rs}200` },
      { name: "Mushroom Noodles", price: `${rs}200` },
      { name: "Schezwan Noodles", price: `${rs}180` },
      { name: "Paneer Schezwan Noodles", price: `${rs}200` },
      { name: "Chinese Chopsuey", price: `${rs}250` },
      { name: "American Chopsuey", price: `${rs}250` },
    ],
  },
  {
    id: "raita",
    title: "Raita",
    banner: assets.imgRaita,
    icon: assets.imgRaita,
    items: [
      { name: "Cucumber Raita", price: `${rs}80` },
      { name: "Mix Veg Raita", price: `${rs}80` },
      { name: "Boondi Raita", price: `${rs}80` },
      { name: "Pineapple Raita", price: `${rs}80` },
      { name: "Onion Raita", price: `${rs}80` },
    ],
  },
  {
    id: "pulao-rice",
    title: "Pulao & Rice",
    banner: assets.imgPulao,
    icon: assets.imgPulao,
    items: [
      { name: "Veg Pulao", price: `${rs}180` },
      { name: "Peas Pulao", price: `${rs}180` },
      { name: "Corn Methi Pulao", price: `${rs}200` },
      { name: "Kashmiri Pulao", price: `${rs}220` },
      { name: "Kaju Pulao", price: `${rs}300` },
      { name: "Kaju Mutter Pulao", price: `${rs}320` },
      { name: "Palak Rice", price: `${rs}180` },
      { name: "Veg Methi Pulao", price: `${rs}200` },
      { name: "Dal Khichdi", price: `${rs}180` },
      { name: "Palak Khichdi", price: `${rs}180` },
      { name: "Curd Rice", price: `${rs}110` },
      { name: "Plain Rice", price: `${rs}70` },
      { name: "Steam Rice", price: `${rs}140` },
    ],
  },
  {
    id: "biryani",
    title: "Rice & Biryani",
    banner: assets.imgBiryani,
    icon: assets.imgBiryani,
    items: [
      { name: "Veg Biryani", price: `${rs}200` },
      { name: "Handi Biryani", price: `${rs}220` },
      { name: "Paneer Biryani", price: `${rs}250` },
      { name: "Mushroom Biryani", price: `${rs}260` },
      { name: "Hyderabadi Biryani", price: `${rs}250` },
      { name: "Mughlai Biryani", price: `${rs}250` },
      { name: "Paneer Tikka Biryani", price: `${rs}260` },
      { name: "Mushroom Tikka Biryani", price: `${rs}270` },
    ],
  },
  {
    id: "fresh-juices",
    title: "Fresh Juices",
    banner: assets.imgJuices,
    icon: assets.imgJuices,
    items: [
      { name: "Mosambi Juice", price: `${rs}110` },
      { name: "Orange Juice", price: `${rs}120` },
      { name: "Watermelon Juice", price: `${rs}100` },
      { name: "ABC Juice (Apple, Beetroot & Carrot)", price: `${rs}120` },
      { name: "Pineapple Juice", price: `${rs}100` },
      { name: "Muskmelon Juice", price: `${rs}110` },
      { name: "Grape Juice", price: `${rs}120` },
    ],
  },
  {
    id: "fresh-fruit-milkshake",
    title: "Fresh Fruit Milkshake",
    banner: assets.imgMilkshake,
    icon: assets.imgMilkshake,
    items: [
      { name: "Banana Milk Shake", price: `${rs}130` },
      { name: "Apple Milk Shake", price: `${rs}150` },
      { name: "Mango Milk Shake (seasonal)", price: `${rs}150` },
      { name: "Butter Fruit Milk Shake", price: `${rs}160` },
    ],
  },
  {
    id: "lime-soda-special",
    title: "Lime / Soda Special",
    banner: assets.imgSoda,
    icon: assets.imgSoda,
    items: [
      { name: "Fresh Lime Soda", price: `${rs}70` },
      { name: "Masala Soda", price: `${rs}80` },
      { name: "Fresh Lime Water", price: `${rs}60` },
      { name: "Fresh Mint Lime", price: `${rs}60` },
      { name: "Fresh Lime Ginger", price: `${rs}70` },
    ],
  },
  {
    id: "ice-cream-scoops",
    title: "Ice Cream Scoops",
    banner: assets.imgIcecream,
    icon: assets.imgIcecream,
    items: [
      { name: "Vanilla", price: `${rs}100` },
      { name: "Strawberry", price: `${rs}110` },
      { name: "Green Pista", price: `${rs}120` },
      { name: "Chocolate", price: `${rs}120` },
      { name: "Mango", price: `${rs}120` },
      { name: "Butter Scotch", price: `${rs}130` },
      { name: "Black Current", price: `${rs}140` },
      { name: "Kesar Pista", price: `${rs}150` },
    ],
  },
  {
    id: "lassy-special",
    title: "Lassy Special",
    banner: assets.imgLassi,
    icon: assets.imgLassi,
    items: [
      { name: "Sweet Lassy", price: `${rs}90` },
      { name: "Dry Fruit Lassy", price: `${rs}130` },
      { name: "Special Lassy", price: `${rs}120` },
      { name: "Butter Milk", price: `${rs}50` },
    ],
  },
];
const galleryImages = [
  "/images/vegmenu/DSC01405_result.webp",
  "/images/vegmenu/DSC01428_result.webp",
  "/images/vegmenu/DSC01385_result.webp",
  "/images/vegmenu/DSC01363_result.webp",
  "/images/vegmenu/DSC01376_result.webp",
  "/images/vegmenu/DSC01367_result.webp",
  "/images/vegmenu/DSC01397_result.webp",
];
export default menuSections;
